In [35]:
#model implementation
input_size=3 # no_of_features
layers=[4,3] #no ofneurons in 1st and 2nd layer
output_size=2


In [36]:
import numpy as np

In [37]:
def softmax(a):
    e_pa = np.exp(a)  #vecctor
    ans=e_pa/np.sum(e_pa,axis=1,keepdims=True)
    return ans

In [39]:
a=np.array([[10,10],
           [20,20]])

a_=softmax(a)
print(a_)

[[0.5 0.5]
 [0.5 0.5]]


In [27]:
import numpy as np


class NeuralNetwork:
    def __init__(self,input_size,layers,output_size):
        np.random.seed(0)
        
        model={}  
        
        
        model['W1']=np.random.randn(input_size,layers[0])   #weighted matrix
        
        model['b1']=np.zeros((1,layers[0]))
        
        model['W2']=np.random.randn(layers[0],layers[1])   #weighted matrix
     
        model['b2']=np.zeros((1,layers[1]))
        
        model['W3']=np.random.randn(layers[1],output_size)   #weighted matrix
        
        model['b3']=np.zeros((1,output_size))
            
        self.model=model
        

In [7]:
 import numpy as np
   


W1=np.random.randn(input_size,layers[0])   #weighted matrix
print(W1)   #matrix size 2x4

[[ 0.13520354 -0.43840167 -0.79735811 -0.42030021]
 [-0.73962534  0.27203055 -0.0572252   0.87748104]
 [-0.57877999 -0.8904311   0.24278987 -1.96147396]]


In [ ]:
def forward(self,x):

    W1,W2,W3 = self.model['W1'],self.model['W2'],self.model['W3']
    b1,b2,b3 = self.model['b1'],self.model['b2'],self.model['b3']
    
    

    z1 = np.dot(x,W1) + b1
    a1 = np.tanh(z1)

    z2 = np.dot(a1,W2) + b2
    a2 = mp.tanh(z2)
    
    z3 = np.dot(a2,W3) + b3
    y_ = softmax(z3)
    
